# Generated by Django 5.2.7 on 2025-10-17 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('roads', '0002_remove_road_speed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speed', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('road', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='roads.road')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
