# Generated by Django 5.2.7 on 2025-10-15 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Road',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_start', models.FloatField(default=0.0)),
                ('lat_start', models.FloatField(default=0.0)),
                ('long_end', models.FloatField(default=0.0)),
                ('lat_end', models.FloatField(default=0.0)),
                ('length', models.FloatField(default=0.0)),
                ('speed', models.FloatField(default=0.0)),
                ('updated_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
